# Generated by Django 6.0.2 on 2026-02-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre obligatorio', max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='Identificador')),
                ('ciudad_salida', models.CharField(max_length=100, verbose_name='Ciudad salida')),
                ('ciudad_llegada', models.CharField(max_length=100, verbose_name='Ciudad llegada')),
                ('terminal_salida', models.CharField(max_length=100, verbose_name='Terminal salida')),
                ('terminal_llegada', models.CharField(max_length=100, verbose_name='Terminal llegada')),
                ('lugar_salida', models.CharField(max_length=100, verbose_name='Lugar salida')),
                ('lugar_llegada', models.CharField(max_length=100, verbose_name='Lugar llegada')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida ida')),
                ('fecha_llegada', models.DateField(verbose_name='Fecha de llegada ida')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Viajes.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'Viajes',
                'ordering': ['-categoria__nombre', '-identificador'],
            },
        ),
        migrations.CreateModel(
            name='ImagenViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='Viajes.viaje')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'imagen_viaje',
            },
        ),
    ]
