# Generated by Django 6.0.2 on 2026-02-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('alojamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='Viajes.alojamientomodel')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'db_table': 'imagen_lojamiento',
            },
        ),
    ]
