# Generated by Django 6.0.2 on 2026-02-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0002_imagenalojamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenalojamiento',
            options={'verbose_name': 'Imagen alojamiento', 'verbose_name_plural': 'Imagenes alojamientos'},
        ),
        migrations.AlterModelOptions(
            name='imagenviaje',
            options={'verbose_name': 'Imagen viaje', 'verbose_name_plural': 'Imagenes viajes'},
        ),
        migrations.AlterModelTable(
            name='imagenalojamiento',
            table='imagen_alojamiento',
        ),
    ]
