# Generated by Django 6.0.2 on 2026-02-19 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0003_alter_imagenalojamiento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseñasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='Identificador')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('puntuacion', models.IntegerField(verbose_name='Puntuacion')),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Viajes.alojamientomodel', verbose_name='Alojamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'Reseñas',
            },
        ),
    ]
