# Generated by Django 6.0.2 on 2026-02-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0004_reseñasmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñasmodel',
            name='puntuacion',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, verbose_name='Puntuacion'),
        ),
    ]
