# Generated by Django 6.0.2 on 2026-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0005_alter_reseñasmodel_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñasmodel',
            name='puntuacion',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Puntuacion'),
        ),
    ]
