# Generated by Django 6.0.2 on 2026-02-19 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0006_alter_reseñasmodel_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenReseñas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/', verbose_name='Imagen')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('reseña', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Imagen_reseña', to='Viajes.reseñasmodel')),
            ],
            options={
                'verbose_name': 'Imagen reseña',
                'verbose_name_plural': 'Imagenes reseñas',
                'db_table': 'imagen_reseña',
            },
        ),
    ]
