# Generated by Django 6.0.2 on 2026-02-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodel',
            old_name='Nacionalidad',
            new_name='nacionalidad',
        ),
    ]
