# Generated by Django 6.0.2 on 2026-02-05 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_nacionalidad_infomodel_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='infoPersonal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.infomodel'),
        ),
    ]
