# Generated by Django 6.0.2 on 2026-02-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_infopersonal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='infoPersonal',
            new_name='info_personal',
        ),
    ]
