# Generated by Django 6.0.2 on 2026-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_rename_infopersonal_customuser_info_personal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomodel',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='infomodel',
            name='nacionalidad',
            field=models.CharField(max_length=30),
        ),
    ]
