# Generated by Django 6.0.2 on 2026-02-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_fechanacimiento_infomodel_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
