# Generated by Django 6.0.2 on 2026-02-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_infomodel_pasaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomodel',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
