# Generated by Django 6.0.2 on 2026-02-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_infomodel_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia', models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia')),
                ('preferencia_dos', models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia')),
                ('preferencia_tres', models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia')),
                ('preferencia_cuatro', models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia')),
            ],
            options={
                'verbose_name': 'preferencia',
                'verbose_name_plural': 'preferencias',
                'db_table': 'preferencias',
            },
        ),
    ]
