# Generated by Django 6.0.2 on 2026-02-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_preferencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia 1'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia_cuatro',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia 4'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia_dos',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia 2'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia_tres',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto')], max_length=20, verbose_name='Preferencia 3'),
        ),
    ]
