# Generated by Django 6.0.2 on 2026-02-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_preferencias_preferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencias',
            name='preferencia_cinco',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto'), ('ESPIRITUALIDAD', 'Espiritualidad'), ('ARTE', 'Arte'), ('SALUD MENTAL', 'Salud'), ('JUEGOS MESA', 'Juegos'), ('VIDEOJUEGOS', 'Videojuego'), ('ACAMPADA', 'Acampada'), ('CRUELTY FREE', 'Cruelty'), ('QUEDAR CON AMIGOS', 'Quedar'), ('VOLUNTARIADO', 'Voluntariado'), ('LGBTQ+', 'Lgbtq')], default='viaje', max_length=20, verbose_name='Preferencia 5'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto'), ('ESPIRITUALIDAD', 'Espiritualidad'), ('ARTE', 'Arte'), ('SALUD MENTAL', 'Salud'), ('JUEGOS MESA', 'Juegos'), ('VIDEOJUEGOS', 'Videojuego'), ('ACAMPADA', 'Acampada'), ('CRUELTY FREE', 'Cruelty'), ('QUEDAR CON AMIGOS', 'Quedar'), ('VOLUNTARIADO', 'Voluntariado'), ('LGBTQ+', 'Lgbtq')], max_length=20, verbose_name='Preferencia 1'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia_cuatro',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto'), ('ESPIRITUALIDAD', 'Espiritualidad'), ('ARTE', 'Arte'), ('SALUD MENTAL', 'Salud'), ('JUEGOS MESA', 'Juegos'), ('VIDEOJUEGOS', 'Videojuego'), ('ACAMPADA', 'Acampada'), ('CRUELTY FREE', 'Cruelty'), ('QUEDAR CON AMIGOS', 'Quedar'), ('VOLUNTARIADO', 'Voluntariado'), ('LGBTQ+', 'Lgbtq')], max_length=20, verbose_name='Preferencia 4'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia_dos',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto'), ('ESPIRITUALIDAD', 'Espiritualidad'), ('ARTE', 'Arte'), ('SALUD MENTAL', 'Salud'), ('JUEGOS MESA', 'Juegos'), ('VIDEOJUEGOS', 'Videojuego'), ('ACAMPADA', 'Acampada'), ('CRUELTY FREE', 'Cruelty'), ('QUEDAR CON AMIGOS', 'Quedar'), ('VOLUNTARIADO', 'Voluntariado'), ('LGBTQ+', 'Lgbtq')], max_length=20, verbose_name='Preferencia 2'),
        ),
        migrations.AlterField(
            model_name='preferencias',
            name='preferencia_tres',
            field=models.CharField(choices=[('VIAJE EN CARRETERA', 'Viaje'), ('CINE', 'Cine'), ('FOTOGRAFIA', 'Foto'), ('ESPIRITUALIDAD', 'Espiritualidad'), ('ARTE', 'Arte'), ('SALUD MENTAL', 'Salud'), ('JUEGOS MESA', 'Juegos'), ('VIDEOJUEGOS', 'Videojuego'), ('ACAMPADA', 'Acampada'), ('CRUELTY FREE', 'Cruelty'), ('QUEDAR CON AMIGOS', 'Quedar'), ('VOLUNTARIADO', 'Voluntariado'), ('LGBTQ+', 'Lgbtq')], max_length=20, verbose_name='Preferencia 3'),
        ),
    ]
