# Generated by Django 6.0.2 on 2026-02-08 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_preferencias_preferencia_cinco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prefer_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.preferencias'),
        ),
    ]
