# Generated by Django 6.0.2 on 2026-02-08 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_customuser_prefer_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='prefer_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.preferencias', verbose_name='Preferencias'),
        ),
    ]
