# Generated by Django 6.0.2 on 2026-02-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_customuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencias',
            name='preferencia',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='preferencia_cinco',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='preferencia_cuatro',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='preferencia_dos',
        ),
        migrations.RemoveField(
            model_name='preferencias',
            name='preferencia_tres',
        ),
        migrations.AddField(
            model_name='preferencias',
            name='nombre',
            field=models.CharField(default='Preferencia', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='prefer_personal',
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefer_personal',
            field=models.ManyToManyField(to='Users.preferencias', verbose_name='Preferencias'),
        ),
    ]
