# Generated by Django 6.0.2 on 2026-02-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_remove_preferencias_preferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='paises',
            field=models.ManyToManyField(to='Users.paisesmodel', verbose_name='Paises'),
        ),
    ]
